import { and, eq, isNull } from 'drizzle-orm';

import { PANTRY_STAPLE_SEED_KEYS } from '../../domain/pantryStaples';
import { MONTHLY_SHELF_LIFE_THRESHOLD_DAYS } from '../../domain/shopping';
import { startOfWeek } from '../../domain/week';
import { newId } from '../id';
import { createHouseholdWithDefaults } from '../repositories/households';
import { upsertFood, upsertRecipe } from '../repositories/library';
import { assignManualMeal, generateWeek, setPortionStatus } from '../repositories/plan';
import { createProfile } from '../repositories/profiles';
import {
  addManualShoppingItem,
  addPantryItem,
  generateShoppingList,
  prefillPantryStaples,
  removePantryItem,
  removeShoppingItem,
  setShoppingItemChecked,
  updatePantryItem,
} from '../repositories/shopping';
import { pantryItems, plannedMealPortions, plannedMeals, recipes, shoppingListItems } from '../schema';
import { seedIfEmpty } from '../seed';
import { createTestDb } from '../testing/testDb';

const FUTURE_MONDAY = startOfWeek('2031-03-12');

async function createAdult(db: ReturnType<typeof createTestDb>, householdId: string) {
  return createProfile(db, {
    householdId,
    name: 'Adult',
    profileType: 'adult',
    sex: 'male',
    birthDate: '1990-01-01',
    heightCm: 180,
    activityLevel: 'moderate',
    goal: 'maintain',
    weightKg: 80,
    bodyFatPct: 20,
  });
}

describe('shopping list generator (repository)', () => {
  it('generates weekly-horizon items for a short-shelf-life ingredient', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    await createAdult(db, householdId);

    const spinachId = await upsertFood(db, {
      nameCs: 'Špenát',
      nameEn: 'Spinach',
      category: 'vegetables',
      baseUnit: 'g',
      kcalPer100: 23,
      proteinPer100: 2.9,
      carbsPer100: 3.6,
      fatPer100: 0.4,
      budget: 'average',
      shelfLifeDays: 4,
      snackSuitable: false,
      dietFlags: ['vegetarian', 'vegan'],
      allergens: [],
    });
    await upsertRecipe(db, {
      nameCs: 'Špenátové rizoto',
      nameEn: 'Spinach risotto',
      category: 'lunch_dinner',
      isSide: false,
      budget: 'average',
      servingsBase: 1,
      ingredients: [{ foodId: spinachId, amount: 150 }],
    });

    // Assign the spinach recipe directly to a slot rather than depending on
    // the generator's random pick – this test only cares about aggregation.
    const spinachRecipe = (await db.select().from(recipes)).find((r) => r.nameEn === 'Spinach risotto')!;
    await assignManualMeal(db, householdId, FUTURE_MONDAY, 'lunch', null, 'recipe', spinachRecipe.id);

    await generateShoppingList(db, householdId, FUTURE_MONDAY);

    const items = await db
      .select()
      .from(shoppingListItems)
      .where(and(eq(shoppingListItems.householdId, householdId), isNull(shoppingListItems.deletedAt)));
    const spinachItem = items.find((i) => i.foodId === spinachId);
    expect(spinachItem).toBeDefined();
    expect(spinachItem!.horizon).toBe('weekly');
    expect(spinachItem!.quantity).toBeGreaterThan(0);
    expect(spinachItem!.autoGenerated).toBe(true);
  });

  it('projects a long-shelf-life ingredient to a monthly batch quantity', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    await createAdult(db, householdId);

    const riceId = await upsertFood(db, {
      nameCs: 'Rýže',
      nameEn: 'Rice',
      category: 'grains',
      baseUnit: 'g',
      kcalPer100: 356,
      proteinPer100: 6.7,
      carbsPer100: 79,
      fatPer100: 0.6,
      budget: 'cheap',
      shelfLifeDays: MONTHLY_SHELF_LIFE_THRESHOLD_DAYS,
      snackSuitable: false,
      dietFlags: ['vegetarian', 'vegan'],
      allergens: [],
    });
    await upsertRecipe(db, {
      nameCs: 'Rýže s kuřetem',
      nameEn: 'Rice with chicken',
      category: 'lunch_dinner',
      isSide: false,
      budget: 'average',
      servingsBase: 1,
      ingredients: [{ foodId: riceId, amount: 100 }],
    });

    const riceRecipe = (await db.select().from(recipes)).find((r) => r.nameEn === 'Rice with chicken')!;
    await assignManualMeal(db, householdId, FUTURE_MONDAY, 'lunch', null, 'recipe', riceRecipe.id);

    await generateShoppingList(db, householdId, FUTURE_MONDAY);

    const items = await db.select().from(shoppingListItems).where(eq(shoppingListItems.householdId, householdId));
    const riceItem = items.find((i) => i.foodId === riceId);
    expect(riceItem).toBeDefined();
    expect(riceItem!.horizon).toBe('monthly');
    // The recipe is scaled to the profile's lunch calorie target (not a flat
    // 1:1), so just assert the batching produced a sensible positive amount;
    // the exact ×4 monthly-projection math is covered by the pure domain test.
    expect(riceItem!.quantity).toBeGreaterThan(0);
  });

  it('nets the need against pantry stock and regeneration replaces only auto items', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    await createAdult(db, householdId);
    await seedIfEmpty(db);
    await generateWeek(db, householdId, FUTURE_MONDAY, 5);

    await addManualShoppingItem(db, householdId, {
      customName: 'Birthday candles',
      quantity: 1,
      unit: 'pack',
      horizon: 'weekly',
    });

    await generateShoppingList(db, householdId, FUTURE_MONDAY);
    await generateShoppingList(db, householdId, FUTURE_MONDAY); // regenerate again

    const items = await db
      .select()
      .from(shoppingListItems)
      .where(and(eq(shoppingListItems.householdId, householdId), isNull(shoppingListItems.deletedAt)));

    const manualItems = items.filter((i) => !i.autoGenerated);
    expect(manualItems).toHaveLength(1);
    expect(manualItems[0].customName).toBe('Birthday candles');

    const autoItems = items.filter((i) => i.autoGenerated);
    expect(autoItems.length).toBeGreaterThan(0);
    // No duplicate auto rows for the same food after a second regeneration.
    const foodIds = autoItems.map((i) => i.foodId);
    expect(new Set(foodIds).size).toBe(foodIds.length);
  });

  it('checking an item with a food moves its quantity into the pantry', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    const eggId = await upsertFood(db, {
      nameCs: 'Vejce',
      nameEn: 'Egg',
      category: 'eggs',
      baseUnit: 'piece',
      gramsPerPiece: 55,
      kcalPer100: 143,
      proteinPer100: 12.6,
      carbsPer100: 0.7,
      fatPer100: 9.5,
      budget: 'cheap',
      shelfLifeDays: 28,
      snackSuitable: false,
      dietFlags: ['vegetarian'],
      allergens: ['eggs'],
    });
    await addManualShoppingItem(db, householdId, {
      foodId: eggId,
      quantity: 10,
      unit: 'piece',
      horizon: 'weekly',
    });
    const [item] = await db.select().from(shoppingListItems).where(eq(shoppingListItems.foodId, eggId));

    await setShoppingItemChecked(db, item.id, true);

    const [itemAfter] = await db.select().from(shoppingListItems).where(eq(shoppingListItems.id, item.id));
    expect(itemAfter.checked).toBe(true);

    const pantryRows = await db.select().from(pantryItems).where(eq(pantryItems.foodId, eggId));
    expect(pantryRows).toHaveLength(1);
    expect(pantryRows[0].quantity).toBe(10);
    expect(pantryRows[0].expiresAt).not.toBeNull();
  });

  it('re-checking an already-checked item does not duplicate its pantry stock (D1 regression)', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    const milkId = await upsertFood(db, {
      nameCs: 'Mléko',
      nameEn: 'Milk',
      category: 'dairy',
      baseUnit: 'ml',
      kcalPer100: 42,
      proteinPer100: 3.4,
      carbsPer100: 5,
      fatPer100: 1,
      budget: 'cheap',
      shelfLifeDays: 7,
      snackSuitable: false,
      dietFlags: ['vegetarian'],
      allergens: ['lactose'],
    });
    await addManualShoppingItem(db, householdId, {
      foodId: milkId,
      quantity: 1000,
      unit: 'ml',
      horizon: 'weekly',
    });
    const [item] = await db.select().from(shoppingListItems).where(eq(shoppingListItems.foodId, milkId));

    // Simulates a double-tap / repeated call while already checked.
    await setShoppingItemChecked(db, item.id, true);
    await setShoppingItemChecked(db, item.id, true);
    await setShoppingItemChecked(db, item.id, true);

    const pantryRows = await db.select().from(pantryItems).where(eq(pantryItems.foodId, milkId));
    expect(pantryRows).toHaveLength(1);
    expect(pantryRows[0].quantity).toBe(1000);
  });

  it('supports manual pantry CRUD', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    const milkId = await upsertFood(db, {
      nameCs: 'Mléko',
      nameEn: 'Milk',
      category: 'dairy',
      baseUnit: 'ml',
      kcalPer100: 46,
      proteinPer100: 3.4,
      carbsPer100: 4.8,
      fatPer100: 1.5,
      budget: 'cheap',
      shelfLifeDays: 7,
      snackSuitable: false,
      dietFlags: ['vegetarian'],
      allergens: ['lactose'],
    });

    await addPantryItem(db, householdId, { foodId: milkId, quantity: 1000 });
    const [row] = await db.select().from(pantryItems).where(eq(pantryItems.foodId, milkId));
    expect(row.expiresAt).not.toBeNull();

    await updatePantryItem(db, row.id, { quantity: 500 });
    const [updated] = await db.select().from(pantryItems).where(eq(pantryItems.id, row.id));
    expect(updated.quantity).toBe(500);

    await removePantryItem(db, row.id);
    const remaining = await db
      .select()
      .from(pantryItems)
      .where(and(eq(pantryItems.id, row.id), isNull(pantryItems.deletedAt)));
    expect(remaining).toHaveLength(0);
  });

  it('marking a meal eaten deducts its ingredients from pantry stock, and un-marking it restocks them', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    const profileId = await createAdult(db, householdId);

    const kefirId = await upsertFood(db, {
      nameCs: 'Kefír',
      nameEn: 'Kefir',
      category: 'dairy',
      baseUnit: 'ml',
      kcalPer100: 60,
      proteinPer100: 3.3,
      carbsPer100: 4,
      fatPer100: 3.5,
      budget: 'cheap',
      shelfLifeDays: 10,
      snackSuitable: true,
      dietFlags: ['vegetarian'],
      allergens: ['lactose'],
    });
    await upsertRecipe(db, {
      nameCs: 'Kefírové smoothie',
      nameEn: 'Kefir smoothie',
      category: 'snack',
      isSide: false,
      budget: 'cheap',
      servingsBase: 1,
      ingredients: [{ foodId: kefirId, amount: 300 }],
    });
    const smoothie = (await db.select().from(recipes)).find((r) => r.nameEn === 'Kefir smoothie')!;

    await addPantryItem(db, householdId, { foodId: kefirId, quantity: 500 });

    // Snack-slot portions always get multiplier 1, so the deducted amount is exactly the recipe's ingredient amount.
    await assignManualMeal(db, householdId, FUTURE_MONDAY, 'snack_morning', profileId, 'recipe', smoothie.id);
    const [meal] = await db
      .select()
      .from(plannedMeals)
      .where(and(eq(plannedMeals.householdId, householdId), eq(plannedMeals.slotKey, 'snack_morning')));
    const [portion] = await db
      .select()
      .from(plannedMealPortions)
      .where(eq(plannedMealPortions.plannedMealId, meal.id));

    await setPortionStatus(db, portion.id, 'eaten');

    const [afterEaten] = await db
      .select()
      .from(pantryItems)
      .where(and(eq(pantryItems.foodId, kefirId), isNull(pantryItems.deletedAt)));
    expect(afterEaten.quantity).toBe(200);

    await setPortionStatus(db, portion.id, 'planned');

    const afterUndo = await db
      .select()
      .from(pantryItems)
      .where(and(eq(pantryItems.foodId, kefirId), isNull(pantryItems.deletedAt)));
    const totalAfterUndo = afterUndo.reduce((sum, row) => sum + row.quantity, 0);
    expect(totalAfterUndo).toBe(500);
  });

  it('removeShoppingItem soft-deletes the row', async () => {
    const db = createTestDb();
    const householdId = await createHouseholdWithDefaults(db, 'Test');
    await addManualShoppingItem(db, householdId, {
      customName: 'Napkins',
      quantity: 1,
      unit: 'pack',
      horizon: 'weekly',
    });
    const [item] = await db.select().from(shoppingListItems).where(eq(shoppingListItems.householdId, householdId));
    await removeShoppingItem(db, item.id);
    const remaining = await db
      .select()
      .from(shoppingListItems)
      .where(and(eq(shoppingListItems.id, item.id), isNull(shoppingListItems.deletedAt)));
    expect(remaining).toHaveLength(0);
  });

  describe('prefillPantryStaples', () => {
    it('adds a pantry row for every staple that has a matching seed food and none already in the pantry', async () => {
      const db = createTestDb();
      const householdId = await createHouseholdWithDefaults(db, 'Test');
      await seedIfEmpty(db);

      const result = await prefillPantryStaples(db, householdId);

      expect(result.added).toBe(PANTRY_STAPLE_SEED_KEYS.length);
      expect(result.alreadyPresent).toBe(0);

      const rows = await db.select().from(pantryItems).where(eq(pantryItems.householdId, householdId));
      expect(rows.length).toBe(PANTRY_STAPLE_SEED_KEYS.length);
    });

    it('skips staples already present in the pantry instead of duplicating them', async () => {
      const db = createTestDb();
      const householdId = await createHouseholdWithDefaults(db, 'Test');
      await seedIfEmpty(db);

      await prefillPantryStaples(db, householdId);
      const secondRun = await prefillPantryStaples(db, householdId);

      expect(secondRun.added).toBe(0);
      expect(secondRun.alreadyPresent).toBe(PANTRY_STAPLE_SEED_KEYS.length);

      const rows = await db.select().from(pantryItems).where(eq(pantryItems.householdId, householdId));
      expect(rows.length).toBe(PANTRY_STAPLE_SEED_KEYS.length);
    });
  });
});
