import type { FoodSeed } from './types';

/**
 * Curated seed foods. Nutrition per 100 g / 100 ml, sourced from USDA
 * FoodData Central (Foundation/SR Legacy) and Nutridatabáze.cz for Czech
 * staples. Values are rounded label-style figures; micronutrients are filled
 * only where the source is confident – missing means unknown, never zero.
 */
export const seedFoods: FoodSeed[] = [
  // --- meat & fish ---------------------------------------------------------
  { key: 'chicken_breast', nameCs: 'Kuřecí prsa (syrová)', nameEn: 'Chicken breast (raw)', category: 'meat', baseUnit: 'g', kcalPer100: 120, proteinPer100: 22.5, carbsPer100: 0, fatPer100: 2.6, fiberPer100: 0, micronutrients: { b12Ug: 0.2 }, budget: 'average', shelfLifeDays: 3, storage: 'fridge', source: 'usda' },
  { key: 'chicken_thigh', nameCs: 'Kuřecí stehna bez kůže', nameEn: 'Chicken thigh, skinless', category: 'meat', baseUnit: 'g', kcalPer100: 121, proteinPer100: 19.7, carbsPer100: 0, fatPer100: 4.1, fiberPer100: 0, budget: 'cheap', shelfLifeDays: 3, storage: 'fridge', source: 'usda' },
  { key: 'beef_lean', nameCs: 'Hovězí zadní (libové)', nameEn: 'Beef, lean cut', category: 'meat', baseUnit: 'g', kcalPer100: 130, proteinPer100: 21.3, carbsPer100: 0, fatPer100: 4.6, fiberPer100: 0, micronutrients: { ironMg: 2.2, b12Ug: 2.6 }, budget: 'expensive', shelfLifeDays: 3, storage: 'fridge', source: 'usda' },
  { key: 'ground_beef_10', nameCs: 'Mleté hovězí 10 % tuku', nameEn: 'Ground beef, 10 % fat', category: 'meat', baseUnit: 'g', kcalPer100: 176, proteinPer100: 20, carbsPer100: 0, fatPer100: 10, fiberPer100: 0, micronutrients: { ironMg: 2.2, b12Ug: 2.2 }, budget: 'average', shelfLifeDays: 2, storage: 'fridge', source: 'usda' },
  { key: 'pork_loin', nameCs: 'Vepřová kýta (libová)', nameEn: 'Pork, lean leg', category: 'meat', baseUnit: 'g', kcalPer100: 143, proteinPer100: 21, carbsPer100: 0, fatPer100: 6.2, fiberPer100: 0, micronutrients: { b12Ug: 0.7 }, budget: 'average', shelfLifeDays: 3, storage: 'fridge', source: 'nutridatabaze' },
  { key: 'salmon', nameCs: 'Losos (filet)', nameEn: 'Salmon fillet', category: 'fish', baseUnit: 'g', kcalPer100: 208, proteinPer100: 20.4, carbsPer100: 0, fatPer100: 13.4, fiberPer100: 0, micronutrients: { vitaminDUg: 11, b12Ug: 3.2, omega3G: 2.2 }, budget: 'expensive', shelfLifeDays: 2, storage: 'fridge', source: 'usda' },
  { key: 'cod', nameCs: 'Treska (filet)', nameEn: 'Cod fillet', category: 'fish', baseUnit: 'g', kcalPer100: 82, proteinPer100: 17.8, carbsPer100: 0, fatPer100: 0.7, fiberPer100: 0, micronutrients: { b12Ug: 0.9, vitaminDUg: 1 }, budget: 'average', shelfLifeDays: 2, storage: 'freezer', source: 'usda' },
  { key: 'tuna_canned', nameCs: 'Tuňák v konzervě (ve vlastní šťávě)', nameEn: 'Canned tuna in brine', category: 'fish', baseUnit: 'g', kcalPer100: 116, proteinPer100: 25.5, carbsPer100: 0, fatPer100: 0.8, fiberPer100: 0, micronutrients: { b12Ug: 2.5, omega3G: 0.3 }, budget: 'average', shelfLifeDays: 720, storage: 'pantry', source: 'usda' },
  { key: 'ham', nameCs: 'Šunka nejvyšší jakosti', nameEn: 'Premium ham', category: 'meat', baseUnit: 'g', kcalPer100: 107, proteinPer100: 18, carbsPer100: 1, fatPer100: 3.5, fiberPer100: 0, budget: 'average', shelfLifeDays: 7, storage: 'fridge', source: 'nutridatabaze' },

  // --- eggs & dairy --------------------------------------------------------
  { key: 'egg', nameCs: 'Vejce', nameEn: 'Egg', category: 'eggs', baseUnit: 'piece', gramsPerPiece: 55, kcalPer100: 143, proteinPer100: 12.6, carbsPer100: 0.7, fatPer100: 9.5, fiberPer100: 0, micronutrients: { vitaminDUg: 2, b12Ug: 0.9, ironMg: 1.8 }, allergens: ['eggs'], dietFlags: ['vegetarian'], budget: 'cheap', shelfLifeDays: 28, storage: 'fridge', source: 'usda' },
  { key: 'milk_semi', nameCs: 'Mléko polotučné', nameEn: 'Semi-skimmed milk', category: 'dairy', baseUnit: 'ml', kcalPer100: 46, proteinPer100: 3.4, carbsPer100: 4.8, fatPer100: 1.5, fiberPer100: 0, micronutrients: { calciumMg: 120, b12Ug: 0.4 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'cheap', shelfLifeDays: 7, storage: 'fridge', source: 'nutridatabaze' },
  { key: 'greek_yogurt', nameCs: 'Řecký jogurt bílý', nameEn: 'Greek yogurt, plain', category: 'dairy', baseUnit: 'g', kcalPer100: 97, proteinPer100: 9, carbsPer100: 3.9, fatPer100: 5, fiberPer100: 0, micronutrients: { calciumMg: 110, b12Ug: 0.5 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'average', shelfLifeDays: 14, storage: 'fridge', snackSuitable: true, source: 'usda' },
  { key: 'yogurt_white', nameCs: 'Bílý jogurt 3 %', nameEn: 'Plain yogurt, 3 % fat', category: 'dairy', baseUnit: 'g', kcalPer100: 61, proteinPer100: 4.7, carbsPer100: 4.7, fatPer100: 3, fiberPer100: 0, micronutrients: { calciumMg: 130 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'cheap', shelfLifeDays: 14, storage: 'fridge', snackSuitable: true, source: 'nutridatabaze' },
  { key: 'cottage_semi', nameCs: 'Tvaroh polotučný', nameEn: 'Quark, semi-fat', category: 'dairy', baseUnit: 'g', kcalPer100: 96, proteinPer100: 12, carbsPer100: 4, fatPer100: 3.8, fiberPer100: 0, micronutrients: { calciumMg: 90 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'cheap', shelfLifeDays: 10, storage: 'fridge', snackSuitable: true, source: 'nutridatabaze' },
  { key: 'quark_lowfat', nameCs: 'Tvaroh odtučněný', nameEn: 'Quark, low-fat', category: 'dairy', baseUnit: 'g', kcalPer100: 68, proteinPer100: 12, carbsPer100: 4, fatPer100: 0.5, fiberPer100: 0, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'cheap', shelfLifeDays: 10, storage: 'fridge', snackSuitable: true, source: 'nutridatabaze' },
  { key: 'cheese_edam', nameCs: 'Eidam 30 %', nameEn: 'Edam cheese, 30 %', category: 'dairy', baseUnit: 'g', kcalPer100: 264, proteinPer100: 27, carbsPer100: 2, fatPer100: 17, fiberPer100: 0, micronutrients: { calciumMg: 800, b12Ug: 1.5 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'average', shelfLifeDays: 21, storage: 'fridge', source: 'nutridatabaze' },
  { key: 'mozzarella', nameCs: 'Mozzarella', nameEn: 'Mozzarella', category: 'dairy', baseUnit: 'g', kcalPer100: 253, proteinPer100: 18, carbsPer100: 2, fatPer100: 19, fiberPer100: 0, micronutrients: { calciumMg: 500 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'average', shelfLifeDays: 14, storage: 'fridge', source: 'usda' },
  { key: 'feta', nameCs: 'Feta / balkánský sýr', nameEn: 'Feta cheese', category: 'dairy', baseUnit: 'g', kcalPer100: 264, proteinPer100: 14.2, carbsPer100: 4.1, fatPer100: 21.3, fiberPer100: 0, micronutrients: { calciumMg: 490 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'average', shelfLifeDays: 21, storage: 'fridge', source: 'usda' },
  { key: 'butter', nameCs: 'Máslo', nameEn: 'Butter', category: 'fats', baseUnit: 'g', kcalPer100: 744, proteinPer100: 0.7, carbsPer100: 0.7, fatPer100: 82, fiberPer100: 0, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'average', shelfLifeDays: 60, storage: 'fridge', source: 'nutridatabaze' },
  { key: 'kefir', nameCs: 'Kefír', nameEn: 'Kefir', category: 'dairy', baseUnit: 'ml', kcalPer100: 55, proteinPer100: 3.3, carbsPer100: 4.5, fatPer100: 2.5, fiberPer100: 0, micronutrients: { calciumMg: 120, b12Ug: 0.3 }, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'cheap', shelfLifeDays: 10, storage: 'fridge', snackSuitable: true, source: 'nutridatabaze' },
  { key: 'protein_whey', nameCs: 'Syrovátkový protein', nameEn: 'Whey protein powder', category: 'supplements', baseUnit: 'g', kcalPer100: 380, proteinPer100: 78, carbsPer100: 6, fatPer100: 5, fiberPer100: 0, allergens: ['lactose'], dietFlags: ['vegetarian'], budget: 'expensive', shelfLifeDays: 365, storage: 'pantry', snackSuitable: true, source: 'usda' },

  // --- grains & carbs ------------------------------------------------------
  { key: 'oats', nameCs: 'Ovesné vločky', nameEn: 'Rolled oats', category: 'grains', baseUnit: 'g', kcalPer100: 379, proteinPer100: 13.2, carbsPer100: 67.7, fatPer100: 6.5, fiberPer100: 10.1, micronutrients: { ironMg: 4.3 }, allergens: ['gluten'], dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 365, storage: 'pantry', source: 'usda' },
  { key: 'rice_white_dry', nameCs: 'Rýže bílá (suchá)', nameEn: 'White rice (dry)', category: 'grains', baseUnit: 'g', kcalPer100: 356, proteinPer100: 6.7, carbsPer100: 79, fatPer100: 0.6, fiberPer100: 1.3, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 365, storage: 'pantry', source: 'usda' },
  { key: 'rice_brown_dry', nameCs: 'Rýže natural (suchá)', nameEn: 'Brown rice (dry)', category: 'grains', baseUnit: 'g', kcalPer100: 362, proteinPer100: 7.5, carbsPer100: 76, fatPer100: 2.7, fiberPer100: 3.6, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 365, storage: 'pantry', source: 'usda' },
  { key: 'pasta_dry', nameCs: 'Těstoviny semolinové (suché)', nameEn: 'Pasta, semolina (dry)', category: 'grains', baseUnit: 'g', kcalPer100: 371, proteinPer100: 13, carbsPer100: 75, fatPer100: 1.5, fiberPer100: 3, allergens: ['gluten'], dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 720, storage: 'pantry', source: 'usda' },
  { key: 'pasta_wholegrain', nameCs: 'Těstoviny celozrnné (suché)', nameEn: 'Whole-wheat pasta (dry)', category: 'grains', baseUnit: 'g', kcalPer100: 348, proteinPer100: 13.4, carbsPer100: 70, fatPer100: 2.5, fiberPer100: 8.4, allergens: ['gluten'], dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 720, storage: 'pantry', source: 'usda' },
  { key: 'potatoes', nameCs: 'Brambory', nameEn: 'Potatoes', category: 'vegetables', baseUnit: 'g', kcalPer100: 77, proteinPer100: 2, carbsPer100: 17, fatPer100: 0.1, fiberPer100: 2.2, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 30, storage: 'pantry', source: 'usda' },
  { key: 'sweet_potato', nameCs: 'Batáty', nameEn: 'Sweet potatoes', category: 'vegetables', baseUnit: 'g', kcalPer100: 86, proteinPer100: 1.6, carbsPer100: 20, fatPer100: 0.1, fiberPer100: 3, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 21, storage: 'pantry', source: 'usda' },
  { key: 'bread_wholegrain', nameCs: 'Chléb celozrnný', nameEn: 'Whole-grain bread', category: 'bakery', baseUnit: 'g', kcalPer100: 247, proteinPer100: 13, carbsPer100: 41, fatPer100: 3.4, fiberPer100: 6, micronutrients: { ironMg: 2.5 }, allergens: ['gluten'], dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 4, storage: 'pantry', source: 'usda' },
  { key: 'rohlik', nameCs: 'Rohlík', nameEn: 'Czech white roll', category: 'bakery', baseUnit: 'piece', gramsPerPiece: 43, kcalPer100: 296, proteinPer100: 9, carbsPer100: 58, fatPer100: 2.4, fiberPer100: 2.2, allergens: ['gluten'], dietFlags: ['vegetarian'], budget: 'cheap', shelfLifeDays: 2, storage: 'pantry', source: 'nutridatabaze' },
  { key: 'couscous_dry', nameCs: 'Kuskus (suchý)', nameEn: 'Couscous (dry)', category: 'grains', baseUnit: 'g', kcalPer100: 376, proteinPer100: 12.8, carbsPer100: 77, fatPer100: 0.6, fiberPer100: 5, allergens: ['gluten'], dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 365, storage: 'pantry', source: 'usda' },
  { key: 'quinoa_dry', nameCs: 'Quinoa (suchá)', nameEn: 'Quinoa (dry)', category: 'grains', baseUnit: 'g', kcalPer100: 368, proteinPer100: 14.1, carbsPer100: 64, fatPer100: 6.1, fiberPer100: 7, micronutrients: { ironMg: 4.6 }, dietFlags: ['vegetarian', 'vegan'], budget: 'expensive', shelfLifeDays: 365, storage: 'pantry', source: 'usda' },
  { key: 'buckwheat_dry', nameCs: 'Pohanka (suchá)', nameEn: 'Buckwheat (dry)', category: 'grains', baseUnit: 'g', kcalPer100: 343, proteinPer100: 13.3, carbsPer100: 71.5, fatPer100: 3.4, fiberPer100: 10, micronutrients: { ironMg: 2.2 }, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 365, storage: 'pantry', source: 'usda' },
  { key: 'lentils_dry', nameCs: 'Čočka (suchá)', nameEn: 'Lentils (dry)', category: 'legumes', baseUnit: 'g', kcalPer100: 352, proteinPer100: 24.6, carbsPer100: 63, fatPer100: 1.1, fiberPer100: 10.7, micronutrients: { ironMg: 6.5 }, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 720, storage: 'pantry', source: 'usda' },
  { key: 'chickpeas_canned', nameCs: 'Cizrna sterilovaná (okapaná)', nameEn: 'Canned chickpeas (drained)', category: 'legumes', baseUnit: 'g', kcalPer100: 139, proteinPer100: 7, carbsPer100: 22, fatPer100: 2.6, fiberPer100: 6, micronutrients: { ironMg: 1.5 }, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 720, storage: 'pantry', source: 'usda' },
  { key: 'beans_red_canned', nameCs: 'Fazole červené sterilované (okapané)', nameEn: 'Canned red kidney beans (drained)', category: 'legumes', baseUnit: 'g', kcalPer100: 99, proteinPer100: 6.7, carbsPer100: 16, fatPer100: 0.5, fiberPer100: 6.3, micronutrients: { ironMg: 1.7 }, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 720, storage: 'pantry', source: 'usda' },
  { key: 'tortilla', nameCs: 'Tortilla pšeničná', nameEn: 'Wheat tortilla', category: 'bakery', baseUnit: 'piece', gramsPerPiece: 62, kcalPer100: 310, proteinPer100: 8.3, carbsPer100: 50, fatPer100: 8, fiberPer100: 3.5, allergens: ['gluten'], dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 30, storage: 'pantry', source: 'usda' },

  // --- vegetables ----------------------------------------------------------
  { key: 'broccoli', nameCs: 'Brokolice', nameEn: 'Broccoli', category: 'vegetables', baseUnit: 'g', kcalPer100: 34, proteinPer100: 2.8, carbsPer100: 6.6, fatPer100: 0.4, fiberPer100: 2.6, micronutrients: { calciumMg: 47, ironMg: 0.7 }, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 5, storage: 'fridge', source: 'usda' },
  { key: 'carrot', nameCs: 'Mrkev', nameEn: 'Carrot', category: 'vegetables', baseUnit: 'g', kcalPer100: 41, proteinPer100: 0.9, carbsPer100: 9.6, fatPer100: 0.2, fiberPer100: 2.8, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 21, storage: 'fridge', source: 'usda' },
  { key: 'tomato', nameCs: 'Rajče', nameEn: 'Tomato', category: 'vegetables', baseUnit: 'g', kcalPer100: 18, proteinPer100: 0.9, carbsPer100: 3.9, fatPer100: 0.2, fiberPer100: 1.2, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 7, storage: 'fridge', source: 'usda' },
  { key: 'cucumber', nameCs: 'Okurka salátová', nameEn: 'Cucumber', category: 'vegetables', baseUnit: 'g', kcalPer100: 15, proteinPer100: 0.7, carbsPer100: 3.6, fatPer100: 0.1, fiberPer100: 0.5, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 7, storage: 'fridge', source: 'usda' },
  { key: 'bell_pepper', nameCs: 'Paprika', nameEn: 'Bell pepper', category: 'vegetables', baseUnit: 'g', kcalPer100: 31, proteinPer100: 1, carbsPer100: 6, fatPer100: 0.3, fiberPer100: 2.1, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 7, storage: 'fridge', source: 'usda' },
  { key: 'onion', nameCs: 'Cibule', nameEn: 'Onion', category: 'vegetables', baseUnit: 'g', kcalPer100: 40, proteinPer100: 1.1, carbsPer100: 9.3, fatPer100: 0.1, fiberPer100: 1.7, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 30, storage: 'pantry', source: 'usda' },
  { key: 'garlic', nameCs: 'Česnek', nameEn: 'Garlic', category: 'vegetables', baseUnit: 'g', kcalPer100: 149, proteinPer100: 6.4, carbsPer100: 33, fatPer100: 0.5, fiberPer100: 2.1, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 60, storage: 'pantry', source: 'usda' },
  { key: 'zucchini', nameCs: 'Cuketa', nameEn: 'Zucchini', category: 'vegetables', baseUnit: 'g', kcalPer100: 17, proteinPer100: 1.2, carbsPer100: 3.1, fatPer100: 0.3, fiberPer100: 1, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 7, storage: 'fridge', source: 'usda' },
  { key: 'spinach', nameCs: 'Špenát (čerstvý)', nameEn: 'Spinach (fresh)', category: 'vegetables', baseUnit: 'g', kcalPer100: 23, proteinPer100: 2.9, carbsPer100: 3.6, fatPer100: 0.4, fiberPer100: 2.2, micronutrients: { ironMg: 2.7, calciumMg: 99 }, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 4, storage: 'fridge', source: 'usda' },
  { key: 'lettuce_mix', nameCs: 'Salátový mix', nameEn: 'Salad mix', category: 'vegetables', baseUnit: 'g', kcalPer100: 17, proteinPer100: 1.2, carbsPer100: 3.3, fatPer100: 0.2, fiberPer100: 1.5, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 4, storage: 'fridge', source: 'usda' },
  { key: 'cabbage', nameCs: 'Zelí hlávkové', nameEn: 'Cabbage', category: 'vegetables', baseUnit: 'g', kcalPer100: 25, proteinPer100: 1.3, carbsPer100: 5.8, fatPer100: 0.1, fiberPer100: 2.5, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 21, storage: 'fridge', source: 'usda' },
  { key: 'cauliflower', nameCs: 'Květák', nameEn: 'Cauliflower', category: 'vegetables', baseUnit: 'g', kcalPer100: 25, proteinPer100: 1.9, carbsPer100: 5, fatPer100: 0.3, fiberPer100: 2, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 7, storage: 'fridge', source: 'usda' },
  { key: 'peas_frozen', nameCs: 'Hrášek mražený', nameEn: 'Frozen peas', category: 'vegetables', baseUnit: 'g', kcalPer100: 81, proteinPer100: 5.4, carbsPer100: 14.5, fatPer100: 0.4, fiberPer100: 5.7, micronutrients: { ironMg: 1.5 }, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 365, storage: 'freezer', source: 'usda' },
  { key: 'mushrooms', nameCs: 'Žampiony', nameEn: 'Button mushrooms', category: 'vegetables', baseUnit: 'g', kcalPer100: 22, proteinPer100: 3.1, carbsPer100: 3.3, fatPer100: 0.3, fiberPer100: 1, micronutrients: { vitaminDUg: 0.2 }, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 5, storage: 'fridge', source: 'usda' },

  // --- fruit ---------------------------------------------------------------
  { key: 'apple', nameCs: 'Jablko', nameEn: 'Apple', category: 'fruit', baseUnit: 'piece', gramsPerPiece: 180, kcalPer100: 52, proteinPer100: 0.3, carbsPer100: 13.8, fatPer100: 0.2, fiberPer100: 2.4, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 21, storage: 'fridge', snackSuitable: true, source: 'usda' },
  { key: 'banana', nameCs: 'Banán', nameEn: 'Banana', category: 'fruit', baseUnit: 'piece', gramsPerPiece: 120, kcalPer100: 89, proteinPer100: 1.1, carbsPer100: 22.8, fatPer100: 0.3, fiberPer100: 2.6, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 6, storage: 'pantry', snackSuitable: true, source: 'usda' },
  { key: 'orange', nameCs: 'Pomeranč', nameEn: 'Orange', category: 'fruit', baseUnit: 'piece', gramsPerPiece: 130, kcalPer100: 47, proteinPer100: 0.9, carbsPer100: 11.8, fatPer100: 0.1, fiberPer100: 2.4, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 14, storage: 'fridge', snackSuitable: true, source: 'usda' },
  { key: 'blueberries', nameCs: 'Borůvky', nameEn: 'Blueberries', category: 'fruit', baseUnit: 'g', kcalPer100: 57, proteinPer100: 0.7, carbsPer100: 14.5, fatPer100: 0.3, fiberPer100: 2.4, dietFlags: ['vegetarian', 'vegan'], budget: 'expensive', shelfLifeDays: 5, storage: 'fridge', snackSuitable: true, source: 'usda' },
  { key: 'strawberries', nameCs: 'Jahody', nameEn: 'Strawberries', category: 'fruit', baseUnit: 'g', kcalPer100: 32, proteinPer100: 0.7, carbsPer100: 7.7, fatPer100: 0.3, fiberPer100: 2, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 3, storage: 'fridge', snackSuitable: true, source: 'usda' },
  { key: 'lemon', nameCs: 'Citron', nameEn: 'Lemon', category: 'fruit', baseUnit: 'piece', gramsPerPiece: 60, kcalPer100: 29, proteinPer100: 1.1, carbsPer100: 9, fatPer100: 0.3, fiberPer100: 2.8, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 21, storage: 'fridge', source: 'usda' },
  { key: 'avocado', nameCs: 'Avokádo', nameEn: 'Avocado', category: 'fruit', baseUnit: 'piece', gramsPerPiece: 140, kcalPer100: 160, proteinPer100: 2, carbsPer100: 8.5, fatPer100: 14.7, fiberPer100: 6.7, dietFlags: ['vegetarian', 'vegan'], budget: 'expensive', shelfLifeDays: 5, storage: 'pantry', source: 'usda' },

  // --- nuts, fats & other --------------------------------------------------
  { key: 'almonds', nameCs: 'Mandle', nameEn: 'Almonds', category: 'nuts', baseUnit: 'g', kcalPer100: 579, proteinPer100: 21.2, carbsPer100: 21.6, fatPer100: 49.9, fiberPer100: 12.5, micronutrients: { calciumMg: 269, ironMg: 3.7 }, allergens: ['nuts'], dietFlags: ['vegetarian', 'vegan'], budget: 'expensive', shelfLifeDays: 180, storage: 'pantry', snackSuitable: true, source: 'usda' },
  { key: 'walnuts', nameCs: 'Vlašské ořechy', nameEn: 'Walnuts', category: 'nuts', baseUnit: 'g', kcalPer100: 654, proteinPer100: 15.2, carbsPer100: 13.7, fatPer100: 65.2, fiberPer100: 6.7, micronutrients: { omega3G: 9.1, ironMg: 2.9 }, allergens: ['nuts'], dietFlags: ['vegetarian', 'vegan'], budget: 'expensive', shelfLifeDays: 180, storage: 'pantry', snackSuitable: true, source: 'usda' },
  { key: 'peanut_butter', nameCs: 'Arašídové máslo', nameEn: 'Peanut butter', category: 'nuts', baseUnit: 'g', kcalPer100: 588, proteinPer100: 25, carbsPer100: 20, fatPer100: 50, fiberPer100: 6, micronutrients: { ironMg: 1.9 }, allergens: ['peanuts'], dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 270, storage: 'pantry', snackSuitable: true, source: 'usda' },
  { key: 'olive_oil', nameCs: 'Olivový olej', nameEn: 'Olive oil', category: 'fats', baseUnit: 'ml', kcalPer100: 884, proteinPer100: 0, carbsPer100: 0, fatPer100: 100, fiberPer100: 0, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 540, storage: 'pantry', source: 'usda' },
  { key: 'rapeseed_oil', nameCs: 'Řepkový olej', nameEn: 'Rapeseed oil', category: 'fats', baseUnit: 'ml', kcalPer100: 884, proteinPer100: 0, carbsPer100: 0, fatPer100: 100, fiberPer100: 0, micronutrients: { omega3G: 9.1 }, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 540, storage: 'pantry', source: 'usda' },
  { key: 'flaxseed', nameCs: 'Lněné semínko (mleté)', nameEn: 'Flaxseed (ground)', category: 'seeds', baseUnit: 'g', kcalPer100: 534, proteinPer100: 18.3, carbsPer100: 28.9, fatPer100: 42.2, fiberPer100: 27.3, micronutrients: { omega3G: 22.8, calciumMg: 255, ironMg: 5.7 }, dietFlags: ['vegetarian', 'vegan'], budget: 'cheap', shelfLifeDays: 180, storage: 'pantry', source: 'usda' },
  { key: 'honey', nameCs: 'Med', nameEn: 'Honey', category: 'sweeteners', baseUnit: 'g', kcalPer100: 304, proteinPer100: 0.3, carbsPer100: 82, fatPer100: 0, fiberPer100: 0, dietFlags: ['vegetarian'], budget: 'average', shelfLifeDays: 720, storage: 'pantry', source: 'usda' },
  { key: 'dark_chocolate', nameCs: 'Hořká čokoláda 70 %', nameEn: 'Dark chocolate, 70 %', category: 'sweets', baseUnit: 'g', kcalPer100: 546, proteinPer100: 7.8, carbsPer100: 45, fatPer100: 31, fiberPer100: 10.9, micronutrients: { ironMg: 11.9 }, dietFlags: ['vegetarian'], budget: 'average', shelfLifeDays: 365, storage: 'pantry', snackSuitable: true, source: 'usda' },
  { key: 'tofu', nameCs: 'Tofu natural', nameEn: 'Tofu, plain', category: 'legumes', baseUnit: 'g', kcalPer100: 76, proteinPer100: 8, carbsPer100: 1.9, fatPer100: 4.8, fiberPer100: 0.3, micronutrients: { calciumMg: 350, ironMg: 5.4 }, allergens: ['soy'], dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 30, storage: 'fridge', source: 'usda' },
  { key: 'olives', nameCs: 'Olivy', nameEn: 'Olives', category: 'vegetables', baseUnit: 'g', kcalPer100: 115, proteinPer100: 0.8, carbsPer100: 6.3, fatPer100: 10.7, fiberPer100: 3.2, dietFlags: ['vegetarian', 'vegan'], budget: 'average', shelfLifeDays: 365, storage: 'pantry', source: 'usda' },
];
