import type { RecipeSeed } from './types';

/**
 * Curated seed recipes – Mediterranean-inspired baseline mixed with Czech
 * home cooking, per the brief. Amounts are per 1 reference portion in each
 * food's base unit; nutrition is always derived from ingredients.
 */
export const seedRecipes: RecipeSeed[] = [
  // --- breakfasts ----------------------------------------------------------
  {
    key: 'oatmeal_apple_almonds',
    nameCs: 'Ovesná kaše s jablkem a mandlemi',
    nameEn: 'Oatmeal with apple and almonds',
    category: 'breakfast',
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 10,
    instructionsCs: 'Vločky povařte v mléce, ozdobte nakrájeným jablkem a mandlemi.',
    instructionsEn: 'Simmer the oats in milk, top with sliced apple and almonds.',
    tags: ['sweet'],
    ingredients: [
      { foodKey: 'oats', amount: 60 },
      { foodKey: 'milk_semi', amount: 250 },
      { foodKey: 'apple', amount: 1 },
      { foodKey: 'almonds', amount: 15 },
    ],
  },
  {
    key: 'greek_yogurt_bowl',
    nameCs: 'Řecký jogurt s borůvkami, medem a ořechy',
    nameEn: 'Greek yogurt bowl with blueberries, honey and walnuts',
    category: 'breakfast',
    cuisine: 'mediterranean',
    budget: 'average',
    prepTimeMinutes: 5,
    instructionsCs: 'Jogurt promíchejte s medem, posypte borůvkami a ořechy.',
    instructionsEn: 'Stir the honey into the yogurt, top with blueberries and walnuts.',
    tags: ['sweet', 'no_cook'],
    ingredients: [
      { foodKey: 'greek_yogurt', amount: 200 },
      { foodKey: 'blueberries', amount: 100 },
      { foodKey: 'honey', amount: 10 },
      { foodKey: 'walnuts', amount: 15 },
    ],
  },
  {
    key: 'scrambled_eggs_bread',
    nameCs: 'Míchaná vejce s celozrnným chlebem a rajčaty',
    nameEn: 'Scrambled eggs with whole-grain bread and tomatoes',
    category: 'breakfast',
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 10,
    instructionsCs: 'Vejce rozmíchejte a opečte na másle, podávejte s chlebem a rajčaty.',
    instructionsEn: 'Scramble the eggs in butter, serve with bread and tomatoes.',
    tags: ['savoury'],
    ingredients: [
      { foodKey: 'egg', amount: 3 },
      { foodKey: 'butter', amount: 5 },
      { foodKey: 'bread_wholegrain', amount: 80 },
      { foodKey: 'tomato', amount: 100 },
    ],
  },
  {
    key: 'quark_rolls_ham',
    nameCs: 'Rohlíky s tvarohovou pomazánkou a šunkou',
    nameEn: 'Czech rolls with quark spread and ham',
    category: 'breakfast',
    cuisine: 'czech',
    budget: 'cheap',
    prepTimeMinutes: 5,
    instructionsCs: 'Tvaroh osolte a namažte na rohlíky, přidejte šunku a zeleninu.',
    instructionsEn: 'Season the quark, spread on rolls, add ham and vegetables.',
    tags: ['savoury', 'no_cook'],
    ingredients: [
      { foodKey: 'rohlik', amount: 2 },
      { foodKey: 'cottage_semi', amount: 100 },
      { foodKey: 'ham', amount: 50 },
      { foodKey: 'bell_pepper', amount: 80 },
    ],
  },
  {
    key: 'banana_oat_pancakes',
    nameCs: 'Banánovo-ovesné lívance',
    nameEn: 'Banana-oat pancakes',
    category: 'breakfast',
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 15,
    instructionsCs: 'Rozmixujte vločky, banán, vejce a mléko; smažte malé lívance a přelijte medem.',
    instructionsEn: 'Blend oats, banana, eggs and milk; fry small pancakes and drizzle with honey.',
    tags: ['sweet'],
    ingredients: [
      { foodKey: 'oats', amount: 60 },
      { foodKey: 'banana', amount: 1 },
      { foodKey: 'egg', amount: 2 },
      { foodKey: 'milk_semi', amount: 50 },
      { foodKey: 'honey', amount: 10 },
    ],
  },
  {
    key: 'avocado_toast_egg',
    nameCs: 'Toust s avokádem a vejcem',
    nameEn: 'Avocado toast with egg',
    category: 'breakfast',
    cuisine: 'other',
    budget: 'expensive',
    prepTimeMinutes: 10,
    instructionsCs: 'Chléb opečte, rozmačkejte na něj avokádo a navrch dejte sázená vejce.',
    instructionsEn: 'Toast the bread, mash the avocado on top and finish with fried eggs.',
    tags: ['savoury'],
    ingredients: [
      { foodKey: 'bread_wholegrain', amount: 80 },
      { foodKey: 'avocado', amount: 0.5 },
      { foodKey: 'egg', amount: 2 },
    ],
  },
  {
    key: 'kefir_smoothie',
    nameCs: 'Kefírové smoothie s banánem a lněným semínkem',
    nameEn: 'Kefir smoothie with banana and flaxseed',
    category: 'breakfast',
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 5,
    instructionsCs: 'Vše rozmixujte dohladka.',
    instructionsEn: 'Blend everything until smooth.',
    tags: ['sweet', 'no_cook'],
    ingredients: [
      { foodKey: 'kefir', amount: 250 },
      { foodKey: 'banana', amount: 1 },
      { foodKey: 'oats', amount: 30 },
      { foodKey: 'flaxseed', amount: 10 },
    ],
  },

  // --- lunches & dinners ---------------------------------------------------
  {
    key: 'chicken_rice',
    nameCs: 'Kuřecí prsa s rýží a brokolicí',
    nameEn: 'Chicken breast with rice and broccoli',
    category: 'lunch_dinner',
    cuisine: 'mediterranean',
    budget: 'average',
    prepTimeMinutes: 30,
    instructionsCs: 'Kuře opečte na olivovém oleji, podávejte s vařenou rýží a brokolicí v páře.',
    instructionsEn: 'Pan-sear the chicken in olive oil, serve with boiled rice and steamed broccoli.',
    tags: ['mediterranean'],
    ingredients: [
      { foodKey: 'chicken_breast', amount: 150 },
      { foodKey: 'rice_white_dry', amount: 80 },
      { foodKey: 'broccoli', amount: 150 },
      { foodKey: 'olive_oil', amount: 10 },
    ],
  },
  {
    key: 'salmon_potatoes',
    nameCs: 'Pečený losos s bramborami a brokolicí',
    nameEn: 'Baked salmon with potatoes and broccoli',
    category: 'lunch_dinner',
    cuisine: 'mediterranean',
    budget: 'expensive',
    prepTimeMinutes: 35,
    instructionsCs: 'Lososa zakápněte citronem a upečte; podávejte s vařenými bramborami a brokolicí.',
    instructionsEn: 'Bake the salmon with a squeeze of lemon; serve with boiled potatoes and broccoli.',
    tags: ['mediterranean', 'fish'],
    ingredients: [
      { foodKey: 'salmon', amount: 150 },
      { foodKey: 'potatoes', amount: 250 },
      { foodKey: 'broccoli', amount: 150 },
      { foodKey: 'olive_oil', amount: 7 },
      { foodKey: 'lemon', amount: 0.25 },
    ],
  },
  {
    key: 'beef_buckwheat',
    nameCs: 'Dušené hovězí s mrkví a pohankou',
    nameEn: 'Braised beef with carrots and buckwheat',
    category: 'lunch_dinner',
    cuisine: 'czech',
    budget: 'expensive',
    prepTimeMinutes: 90,
    instructionsCs: 'Hovězí poduste s cibulí a mrkví doměkka, podávejte s vařenou pohankou.',
    instructionsEn: 'Braise the beef with onion and carrot until tender, serve over cooked buckwheat.',
    tags: ['czech', 'batch_friendly'],
    mealPrepFriendly: true,
    ingredients: [
      { foodKey: 'beef_lean', amount: 150 },
      { foodKey: 'onion', amount: 50 },
      { foodKey: 'carrot', amount: 100 },
      { foodKey: 'buckwheat_dry', amount: 80 },
      { foodKey: 'rapeseed_oil', amount: 10 },
    ],
  },
  {
    key: 'pasta_tuna',
    nameCs: 'Těstoviny s tuňákem a rajčatovou omáčkou',
    nameEn: 'Pasta with tuna and tomato sauce',
    category: 'lunch_dinner',
    cuisine: 'italian',
    budget: 'cheap',
    prepTimeMinutes: 25,
    instructionsCs: 'Na oleji zpěňte cibuli s česnekem, přidejte rajčata a tuňáka, promíchejte s těstovinami.',
    instructionsEn: 'Sauté onion and garlic, add tomatoes and tuna, toss with the cooked pasta.',
    tags: ['mediterranean', 'fish', 'quick'],
    ingredients: [
      { foodKey: 'pasta_dry', amount: 90 },
      { foodKey: 'tuna_canned', amount: 70 },
      { foodKey: 'tomato', amount: 200 },
      { foodKey: 'onion', amount: 40 },
      { foodKey: 'garlic', amount: 5 },
      { foodKey: 'olive_oil', amount: 10 },
    ],
  },
  {
    key: 'chicken_couscous',
    nameCs: 'Kuřecí kousky s kuskusem a restovanou zeleninou',
    nameEn: 'Chicken with couscous and sautéed vegetables',
    category: 'lunch_dinner',
    cuisine: 'mediterranean',
    budget: 'average',
    prepTimeMinutes: 25,
    instructionsCs: 'Kuře orestujte s cuketou a paprikou, podávejte s kuskusem.',
    instructionsEn: 'Sauté the chicken with zucchini and pepper, serve over couscous.',
    tags: ['mediterranean', 'quick'],
    ingredients: [
      { foodKey: 'chicken_breast', amount: 150 },
      { foodKey: 'couscous_dry', amount: 80 },
      { foodKey: 'zucchini', amount: 100 },
      { foodKey: 'bell_pepper', amount: 100 },
      { foodKey: 'olive_oil', amount: 10 },
    ],
  },
  {
    key: 'lentils_egg',
    nameCs: 'Čočka nakyselo s vejcem a cibulkou',
    nameEn: 'Czech sour lentils with egg and onion',
    category: 'lunch_dinner',
    cuisine: 'czech',
    budget: 'cheap',
    prepTimeMinutes: 40,
    instructionsCs: 'Uvařenou čočku zahustěte, dochuťte octem; podávejte s vejcem a opečenou cibulkou.',
    instructionsEn: 'Cook the lentils, season with vinegar; serve with an egg and fried onion.',
    tags: ['czech', 'vegetarian', 'batch_friendly'],
    mealPrepFriendly: true,
    ingredients: [
      { foodKey: 'lentils_dry', amount: 90 },
      { foodKey: 'egg', amount: 1 },
      { foodKey: 'onion', amount: 50 },
      { foodKey: 'rapeseed_oil', amount: 8 },
    ],
  },
  {
    key: 'pork_potatoes_cabbage',
    nameCs: 'Vepřová kýta s bramborami a dušeným zelím',
    nameEn: 'Pork leg with potatoes and braised cabbage',
    category: 'lunch_dinner',
    cuisine: 'czech',
    budget: 'average',
    prepTimeMinutes: 60,
    instructionsCs: 'Kýtu poduste doměkka, zelí poduste s cibulí, podávejte s bramborami.',
    instructionsEn: 'Braise the pork until tender, stew the cabbage with onion, serve with potatoes.',
    tags: ['czech'],
    ingredients: [
      { foodKey: 'pork_loin', amount: 150 },
      { foodKey: 'potatoes', amount: 250 },
      { foodKey: 'cabbage', amount: 150 },
      { foodKey: 'onion', amount: 30 },
      { foodKey: 'rapeseed_oil', amount: 10 },
    ],
  },
  {
    key: 'cod_sweetpotato',
    nameCs: 'Treska s pečenými batáty a hráškem',
    nameEn: 'Cod with roasted sweet potatoes and peas',
    category: 'lunch_dinner',
    cuisine: 'other',
    budget: 'average',
    prepTimeMinutes: 35,
    instructionsCs: 'Batáty upečte, tresku opečte na másle a podávejte s hráškem.',
    instructionsEn: 'Roast the sweet potatoes, pan-fry the cod in butter, serve with peas.',
    tags: ['fish'],
    ingredients: [
      { foodKey: 'cod', amount: 180 },
      { foodKey: 'sweet_potato', amount: 250 },
      { foodKey: 'peas_frozen', amount: 100 },
      { foodKey: 'butter', amount: 10 },
    ],
  },
  {
    key: 'chickpea_curry',
    nameCs: 'Cizrnové kari s rajčaty a rýží',
    nameEn: 'Chickpea and tomato curry with rice',
    category: 'lunch_dinner',
    cuisine: 'mediterranean',
    budget: 'cheap',
    prepTimeMinutes: 30,
    instructionsCs: 'Cibuli a česnek orestujte, přidejte rajčata a cizrnu, poduste; podávejte s rýží.',
    instructionsEn: 'Sauté onion and garlic, add tomatoes and chickpeas, simmer; serve with rice.',
    tags: ['vegan', 'mediterranean', 'batch_friendly'],
    mealPrepFriendly: true,
    ingredients: [
      { foodKey: 'chickpeas_canned', amount: 200 },
      { foodKey: 'tomato', amount: 200 },
      { foodKey: 'onion', amount: 50 },
      { foodKey: 'garlic', amount: 5 },
      { foodKey: 'rice_white_dry', amount: 70 },
      { foodKey: 'rapeseed_oil', amount: 10 },
    ],
  },
  {
    key: 'tofu_stirfry',
    nameCs: 'Restované tofu se zeleninou a rýží natural',
    nameEn: 'Tofu stir-fry with vegetables and brown rice',
    category: 'lunch_dinner',
    cuisine: 'asian',
    budget: 'average',
    prepTimeMinutes: 25,
    instructionsCs: 'Tofu orestujte dozlatova, přidejte brokolici a mrkev, podávejte s rýží natural.',
    instructionsEn: 'Fry the tofu until golden, add broccoli and carrot, serve with brown rice.',
    tags: ['vegan', 'quick'],
    ingredients: [
      { foodKey: 'tofu', amount: 150 },
      { foodKey: 'broccoli', amount: 150 },
      { foodKey: 'carrot', amount: 80 },
      { foodKey: 'rice_brown_dry', amount: 70 },
      { foodKey: 'rapeseed_oil', amount: 10 },
    ],
  },
  {
    key: 'pasta_chicken_spinach',
    nameCs: 'Celozrnné těstoviny s kuřecím masem a špenátem',
    nameEn: 'Whole-wheat pasta with chicken and spinach',
    category: 'lunch_dinner',
    cuisine: 'italian',
    budget: 'average',
    prepTimeMinutes: 25,
    instructionsCs: 'Kuře orestujte, přidejte špenát a mozzarellu, promíchejte s těstovinami.',
    instructionsEn: 'Sauté the chicken, add spinach and mozzarella, toss with the pasta.',
    tags: ['quick'],
    ingredients: [
      { foodKey: 'pasta_wholegrain', amount: 90 },
      { foodKey: 'chicken_breast', amount: 120 },
      { foodKey: 'spinach', amount: 100 },
      { foodKey: 'mozzarella', amount: 40 },
      { foodKey: 'olive_oil', amount: 8 },
    ],
  },
  {
    key: 'quinoa_feta_salad',
    nameCs: 'Quinoový salát s fetou a olivami',
    nameEn: 'Quinoa salad with feta and olives',
    category: 'lunch_dinner',
    cuisine: 'mediterranean',
    budget: 'expensive',
    prepTimeMinutes: 25,
    instructionsCs: 'Uvařenou quinou smíchejte se zeleninou, fetou a olivami, zakápněte olejem.',
    instructionsEn: 'Mix the cooked quinoa with vegetables, feta and olives, drizzle with oil.',
    tags: ['mediterranean', 'vegetarian', 'no_cook'],
    ingredients: [
      { foodKey: 'quinoa_dry', amount: 80 },
      { foodKey: 'feta', amount: 60 },
      { foodKey: 'cucumber', amount: 100 },
      { foodKey: 'tomato', amount: 150 },
      { foodKey: 'olives', amount: 30 },
      { foodKey: 'olive_oil', amount: 10 },
    ],
  },
  {
    key: 'chicken_tortilla_wrap',
    nameCs: 'Tortilla s kuřecím masem a jogurtovým dresinkem',
    nameEn: 'Chicken tortilla wrap with yogurt dressing',
    category: 'lunch_dinner',
    cuisine: 'mexican',
    budget: 'average',
    prepTimeMinutes: 20,
    instructionsCs: 'Kuře orestujte, zabalte do tortill se zeleninou a jogurtovým dresinkem.',
    instructionsEn: 'Sauté the chicken, wrap in tortillas with vegetables and yogurt dressing.',
    tags: ['quick'],
    ingredients: [
      { foodKey: 'tortilla', amount: 2 },
      { foodKey: 'chicken_breast', amount: 120 },
      { foodKey: 'lettuce_mix', amount: 50 },
      { foodKey: 'tomato', amount: 100 },
      { foodKey: 'greek_yogurt', amount: 50 },
    ],
  },
  {
    key: 'beef_chili',
    nameCs: 'Chilli con carne s fazolemi a rýží',
    nameEn: 'Chili con carne with beans and rice',
    category: 'lunch_dinner',
    cuisine: 'mexican',
    budget: 'average',
    prepTimeMinutes: 45,
    instructionsCs: 'Mleté maso orestujte s cibulí, přidejte rajčata a fazole, duste; podávejte s rýží.',
    instructionsEn: 'Brown the beef with onion, add tomatoes and beans, simmer; serve with rice.',
    tags: ['batch_friendly'],
    mealPrepFriendly: true,
    ingredients: [
      { foodKey: 'ground_beef_10', amount: 120 },
      { foodKey: 'beans_red_canned', amount: 150 },
      { foodKey: 'tomato', amount: 150 },
      { foodKey: 'onion', amount: 50 },
      { foodKey: 'rice_white_dry', amount: 70 },
      { foodKey: 'rapeseed_oil', amount: 8 },
    ],
  },
  {
    key: 'cauliflower_bake',
    nameCs: 'Zapečený květák s vejci a bramborami',
    nameEn: 'Cauliflower bake with eggs and potatoes',
    category: 'lunch_dinner',
    cuisine: 'czech',
    budget: 'cheap',
    prepTimeMinutes: 45,
    instructionsCs: 'Květák a brambory předvařte, zalijte vejci s mlékem a zapečte se sýrem.',
    instructionsEn: 'Par-boil cauliflower and potatoes, pour over the egg-milk mix and bake with cheese.',
    tags: ['czech', 'vegetarian'],
    ingredients: [
      { foodKey: 'cauliflower', amount: 200 },
      { foodKey: 'potatoes', amount: 200 },
      { foodKey: 'egg', amount: 2 },
      { foodKey: 'milk_semi', amount: 50 },
      { foodKey: 'cheese_edam', amount: 30 },
    ],
  },
  {
    key: 'mushroom_risotto',
    nameCs: 'Žampionové rizoto se sýrem',
    nameEn: 'Mushroom risotto with cheese',
    category: 'lunch_dinner',
    cuisine: 'italian',
    budget: 'cheap',
    prepTimeMinutes: 35,
    instructionsCs: 'Cibuli orestujte, přidejte rýži a žampiony, podlévejte a vařte; vmíchejte sýr.',
    instructionsEn: 'Sauté onion, add rice and mushrooms, cook gradually adding water; stir in cheese.',
    tags: ['vegetarian', 'batch_friendly'],
    mealPrepFriendly: true,
    ingredients: [
      { foodKey: 'rice_white_dry', amount: 90 },
      { foodKey: 'mushrooms', amount: 150 },
      { foodKey: 'onion', amount: 50 },
      { foodKey: 'cheese_edam', amount: 40 },
      { foodKey: 'olive_oil', amount: 10 },
    ],
  },

  // --- sides ---------------------------------------------------------------
  {
    key: 'side_rice',
    nameCs: 'Rýže (příloha)',
    nameEn: 'Rice (side)',
    category: 'lunch_dinner',
    isSide: true,
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 15,
    ingredients: [{ foodKey: 'rice_white_dry', amount: 80 }],
  },
  {
    key: 'side_potatoes',
    nameCs: 'Vařené brambory (příloha)',
    nameEn: 'Boiled potatoes (side)',
    category: 'lunch_dinner',
    isSide: true,
    cuisine: 'czech',
    budget: 'cheap',
    prepTimeMinutes: 25,
    ingredients: [{ foodKey: 'potatoes', amount: 250 }],
  },
  {
    key: 'side_bread',
    nameCs: 'Celozrnný chléb (příloha)',
    nameEn: 'Whole-grain bread (side)',
    category: 'lunch_dinner',
    isSide: true,
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 2,
    ingredients: [{ foodKey: 'bread_wholegrain', amount: 80 }],
  },
  {
    key: 'side_salad',
    nameCs: 'Zeleninový salát (příloha)',
    nameEn: 'Green side salad',
    category: 'lunch_dinner',
    isSide: true,
    cuisine: 'mediterranean',
    budget: 'average',
    prepTimeMinutes: 10,
    ingredients: [
      { foodKey: 'lettuce_mix', amount: 80 },
      { foodKey: 'tomato', amount: 100 },
      { foodKey: 'cucumber', amount: 100 },
      { foodKey: 'olive_oil', amount: 5 },
    ],
  },

  // --- snacks --------------------------------------------------------------
  {
    key: 'snack_yogurt_walnuts',
    nameCs: 'Řecký jogurt s ořechy a medem',
    nameEn: 'Greek yogurt with walnuts and honey',
    category: 'snack',
    cuisine: 'mediterranean',
    budget: 'average',
    prepTimeMinutes: 3,
    tags: ['protein', 'no_cook'],
    ingredients: [
      { foodKey: 'greek_yogurt', amount: 150 },
      { foodKey: 'walnuts', amount: 15 },
      { foodKey: 'honey', amount: 5 },
    ],
  },
  {
    key: 'snack_apple_peanut',
    nameCs: 'Jablko s arašídovým máslem',
    nameEn: 'Apple with peanut butter',
    category: 'snack',
    cuisine: 'american',
    budget: 'cheap',
    prepTimeMinutes: 3,
    tags: ['no_cook'],
    ingredients: [
      { foodKey: 'apple', amount: 1 },
      { foodKey: 'peanut_butter', amount: 20 },
    ],
  },
  {
    key: 'snack_protein_shake',
    nameCs: 'Proteinový shake s mlékem',
    nameEn: 'Protein shake with milk',
    category: 'snack',
    cuisine: 'other',
    budget: 'average',
    prepTimeMinutes: 2,
    tags: ['protein', 'no_cook'],
    ingredients: [
      { foodKey: 'protein_whey', amount: 30 },
      { foodKey: 'milk_semi', amount: 250 },
    ],
  },
  {
    key: 'snack_quark_pepper',
    nameCs: 'Tvaroh s paprikou',
    nameEn: 'Quark with bell pepper',
    category: 'snack',
    cuisine: 'czech',
    budget: 'cheap',
    prepTimeMinutes: 3,
    tags: ['protein', 'no_cook'],
    ingredients: [
      { foodKey: 'quark_lowfat', amount: 150 },
      { foodKey: 'bell_pepper', amount: 100 },
    ],
  },
  {
    key: 'snack_banana_chocolate',
    nameCs: 'Banán s hořkou čokoládou',
    nameEn: 'Banana with dark chocolate',
    category: 'snack',
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 2,
    tags: ['sweet', 'no_cook'],
    ingredients: [
      { foodKey: 'banana', amount: 1 },
      { foodKey: 'dark_chocolate', amount: 15 },
    ],
  },
  {
    key: 'snack_nut_mix',
    nameCs: 'Hrst ořechů',
    nameEn: 'Handful of nuts',
    category: 'snack',
    cuisine: 'other',
    budget: 'expensive',
    prepTimeMinutes: 1,
    tags: ['fat', 'no_cook'],
    ingredients: [
      { foodKey: 'almonds', amount: 20 },
      { foodKey: 'walnuts', amount: 10 },
    ],
  },
  {
    key: 'snack_eggs_cucumber',
    nameCs: 'Vejce natvrdo s okurkou',
    nameEn: 'Hard-boiled eggs with cucumber',
    category: 'snack',
    cuisine: 'other',
    budget: 'cheap',
    prepTimeMinutes: 12,
    tags: ['protein'],
    ingredients: [
      { foodKey: 'egg', amount: 2 },
      { foodKey: 'cucumber', amount: 100 },
    ],
  },
  {
    key: 'snack_cottage_strawberries',
    nameCs: 'Tvaroh s jahodami',
    nameEn: 'Quark with strawberries',
    category: 'snack',
    cuisine: 'czech',
    budget: 'average',
    prepTimeMinutes: 3,
    tags: ['protein', 'sweet', 'no_cook'],
    ingredients: [
      { foodKey: 'cottage_semi', amount: 150 },
      { foodKey: 'strawberries', amount: 100 },
    ],
  },
];
