import { and, eq, inArray, isNull } from 'drizzle-orm';

import {
  computeShoppingNeeds,
  deductFromPantryBatches,
  sumWeeklyNeeds,
  type FoodShelfInfo,
  type PlannedMealIngredientNeed,
} from '@/domain/shopping';
import { addDays, startOfWeek, weekDates } from '@/domain/week';

import { newId } from '../id';
import {
  foods,
  pantryItems,
  plannedMealPortions,
  plannedMeals,
  recipeIngredients,
  recipes,
  shoppingListItems,
} from '../schema';
import { nowIso, todayIsoDate } from '../time';
import type { AppDb } from '../types';

/** Every ingredient need for one week's planned meals, in each food's base unit. */
async function loadWeeklyIngredientNeeds(
  db: AppDb,
  householdId: string,
  mondayIso: string,
): Promise<PlannedMealIngredientNeed[]> {
  const dates = weekDates(mondayIso);
  const meals = await db
    .select()
    .from(plannedMeals)
    .where(
      and(
        eq(plannedMeals.householdId, householdId),
        inArray(plannedMeals.date, dates),
        isNull(plannedMeals.deletedAt),
      ),
    );
  if (meals.length === 0) return [];

  const mealIds = meals.map((m) => m.id);
  const portions = await db
    .select()
    .from(plannedMealPortions)
    .where(and(inArray(plannedMealPortions.plannedMealId, mealIds), isNull(plannedMealPortions.deletedAt)));

  const multiplierTotalByMeal = new Map<string, number>();
  for (const portion of portions) {
    multiplierTotalByMeal.set(
      portion.plannedMealId,
      (multiplierTotalByMeal.get(portion.plannedMealId) ?? 0) + portion.multiplier,
    );
  }

  const recipeIds = meals.filter((m) => m.itemType === 'recipe').map((m) => m.itemId);
  const ingredientRows =
    recipeIds.length > 0
      ? await db
          .select()
          .from(recipeIngredients)
          .where(and(inArray(recipeIngredients.recipeId, recipeIds), isNull(recipeIngredients.deletedAt)))
      : [];
  const ingredientsByRecipe = new Map<string, typeof ingredientRows>();
  for (const ingredient of ingredientRows) {
    const list = ingredientsByRecipe.get(ingredient.recipeId) ?? [];
    list.push(ingredient);
    ingredientsByRecipe.set(ingredient.recipeId, list);
  }

  const needs: PlannedMealIngredientNeed[] = [];
  for (const meal of meals) {
    const totalMultiplier = multiplierTotalByMeal.get(meal.id) ?? 0;
    if (totalMultiplier <= 0) continue;
    if (meal.itemType === 'recipe') {
      for (const ingredient of ingredientsByRecipe.get(meal.itemId) ?? []) {
        needs.push({ foodId: ingredient.foodId, amount: ingredient.amount * totalMultiplier });
      }
    } else {
      // Standalone snack food: same "one portion ≈ 100 base units" approximation the generator uses.
      needs.push({ foodId: meal.itemId, amount: 100 * totalMultiplier });
    }
  }
  return needs;
}

/** Non-expired pantry stock per food, in the food's base unit. */
async function loadAvailablePantryStock(db: AppDb, householdId: string): Promise<Map<string, number>> {
  const rows = await db
    .select()
    .from(pantryItems)
    .where(and(eq(pantryItems.householdId, householdId), isNull(pantryItems.deletedAt)));
  const today = todayIsoDate();
  const stock = new Map<string, number>();
  for (const row of rows) {
    if (row.expiresAt !== null && row.expiresAt < today) continue; // already expired – doesn't cover new need
    stock.set(row.foodId, (stock.get(row.foodId) ?? 0) + row.quantity);
  }
  return stock;
}

/**
 * Recomputes the household's auto-generated shopping list from the week
 * containing `referenceDate` (defaults to today), netted against pantry
 * stock. Manually added items are left untouched.
 */
export async function generateShoppingList(
  db: AppDb,
  householdId: string,
  referenceDate: string = todayIsoDate(),
): Promise<void> {
  const monday = startOfWeek(referenceDate);
  const needs = await loadWeeklyIngredientNeeds(db, householdId, monday);
  const weeklyTotals = sumWeeklyNeeds(needs);

  const foodIds = [...weeklyTotals.keys()];
  const foodRows =
    foodIds.length > 0
      ? await db.select().from(foods).where(and(inArray(foods.id, foodIds), isNull(foods.deletedAt)))
      : [];
  const foodsById = new Map<string, FoodShelfInfo>(
    foodRows.map((f) => [f.id, { id: f.id, shelfLifeDays: f.shelfLifeDays, baseUnit: f.baseUnit }]),
  );

  const pantryStock = await loadAvailablePantryStock(db, householdId);
  const shoppingNeeds = computeShoppingNeeds(weeklyTotals, foodsById, pantryStock);

  const now = nowIso();
  await db
    .update(shoppingListItems)
    .set({ deletedAt: now, updatedAt: now })
    .where(
      and(
        eq(shoppingListItems.householdId, householdId),
        eq(shoppingListItems.autoGenerated, true),
        isNull(shoppingListItems.deletedAt),
      ),
    );

  if (shoppingNeeds.length > 0) {
    await db.insert(shoppingListItems).values(
      shoppingNeeds.map((need) => ({
        id: newId(),
        createdAt: now,
        updatedAt: now,
        householdId,
        foodId: need.foodId,
        quantity: need.quantity,
        unit: need.unit,
        horizon: need.horizon,
        checked: false,
        autoGenerated: true,
      })),
    );
  }
}

export type ManualShoppingItemInput = {
  foodId?: string;
  customName?: string;
  quantity?: number;
  unit?: string;
  horizon: 'weekly' | 'monthly';
  note?: string;
};

export async function addManualShoppingItem(
  db: AppDb,
  householdId: string,
  input: ManualShoppingItemInput,
): Promise<void> {
  const now = nowIso();
  await db.insert(shoppingListItems).values({
    id: newId(),
    createdAt: now,
    updatedAt: now,
    householdId,
    foodId: input.foodId ?? null,
    customName: input.customName ?? null,
    quantity: input.quantity ?? null,
    unit: input.unit ?? null,
    horizon: input.horizon,
    checked: false,
    autoGenerated: false,
    note: input.note ?? null,
  });
}

export async function removeShoppingItem(db: AppDb, itemId: string): Promise<void> {
  const now = nowIso();
  await db.update(shoppingListItems).set({ deletedAt: now, updatedAt: now }).where(eq(shoppingListItems.id, itemId));
}

/**
 * Unchecking never reverses a pantry move – undoing an actual purchase is
 * rare and not modeled. Stocking the pantry only happens on an actual
 * false->true transition (checked state read *before* the update), so
 * re-checking an already-checked item, or a duplicate call, can never
 * double-stock the same purchase.
 */
export async function setShoppingItemChecked(db: AppDb, itemId: string, checked: boolean): Promise<void> {
  const [item] = await db.select().from(shoppingListItems).where(eq(shoppingListItems.id, itemId));
  if (!item) return;
  const wasChecked = item.checked;

  const now = nowIso();
  await db.update(shoppingListItems).set({ checked, updatedAt: now }).where(eq(shoppingListItems.id, itemId));

  if (!checked || wasChecked) return;
  if (!item.foodId || item.quantity === null) return; // free-text items have nothing to stock

  const [food] = await db.select().from(foods).where(eq(foods.id, item.foodId));
  const expiresAt = food?.shelfLifeDays != null ? addDays(todayIsoDate(), food.shelfLifeDays) : null;

  await db.insert(pantryItems).values({
    id: newId(),
    createdAt: now,
    updatedAt: now,
    householdId: item.householdId,
    foodId: item.foodId,
    quantity: item.quantity,
    purchasedAt: todayIsoDate(),
    expiresAt,
  });
}

export type PantryItemInput = {
  foodId: string;
  quantity: number;
  expiresAt?: string | null;
};

export async function addPantryItem(db: AppDb, householdId: string, input: PantryItemInput): Promise<void> {
  const now = nowIso();
  let expiresAt = input.expiresAt ?? null;
  if (expiresAt === null) {
    const [food] = await db.select().from(foods).where(eq(foods.id, input.foodId));
    expiresAt = food?.shelfLifeDays != null ? addDays(todayIsoDate(), food.shelfLifeDays) : null;
  }
  await db.insert(pantryItems).values({
    id: newId(),
    createdAt: now,
    updatedAt: now,
    householdId,
    foodId: input.foodId,
    quantity: input.quantity,
    purchasedAt: todayIsoDate(),
    expiresAt,
  });
}

export type IngredientNeed = { foodId: string; amount: number };

/**
 * Ingredient needs for a single meal instance, scaled by its portion
 * multiplier – the same "one portion ≈ 100 base units" approximation used
 * for standalone snack foods in the weekly shopping aggregation.
 */
export async function mealIngredientNeeds(
  db: AppDb,
  meal: { itemType: string; itemId: string },
  multiplier: number,
): Promise<IngredientNeed[]> {
  if (multiplier <= 0) return [];
  if (meal.itemType === 'recipe') {
    const ingredients = await db
      .select()
      .from(recipeIngredients)
      .where(and(eq(recipeIngredients.recipeId, meal.itemId), isNull(recipeIngredients.deletedAt)));
    return ingredients.map((ingredient) => ({ foodId: ingredient.foodId, amount: ingredient.amount * multiplier }));
  }
  return [{ foodId: meal.itemId, amount: 100 * multiplier }];
}

/** Deducts ingredient needs from pantry stock (FIFO by expiry) when a meal is marked eaten. */
export async function deductPantryForConsumption(
  db: AppDb,
  householdId: string,
  needs: IngredientNeed[],
): Promise<void> {
  const now = nowIso();
  for (const need of needs) {
    if (need.amount <= 0) continue;
    const batches = await db
      .select()
      .from(pantryItems)
      .where(
        and(
          eq(pantryItems.householdId, householdId),
          eq(pantryItems.foodId, need.foodId),
          isNull(pantryItems.deletedAt),
        ),
      );
    const updates = deductFromPantryBatches(batches, need.amount);
    for (const update of updates) {
      if (update.quantity <= 0) {
        await db.update(pantryItems).set({ deletedAt: now, updatedAt: now }).where(eq(pantryItems.id, update.id));
      } else {
        await db.update(pantryItems).set({ quantity: update.quantity, updatedAt: now }).where(eq(pantryItems.id, update.id));
      }
    }
  }
}

/** Reverses a consumption deduction (a meal was un-marked as eaten) by adding the amounts back as fresh pantry batches. */
export async function restockPantryForConsumption(
  db: AppDb,
  householdId: string,
  needs: IngredientNeed[],
): Promise<void> {
  for (const need of needs) {
    if (need.amount <= 0) continue;
    await addPantryItem(db, householdId, { foodId: need.foodId, quantity: need.amount });
  }
}

export async function updatePantryItem(
  db: AppDb,
  itemId: string,
  updates: { quantity?: number; expiresAt?: string | null },
): Promise<void> {
  const now = nowIso();
  await db
    .update(pantryItems)
    .set({ ...updates, updatedAt: now })
    .where(eq(pantryItems.id, itemId));
}

export async function removePantryItem(db: AppDb, itemId: string): Promise<void> {
  const now = nowIso();
  await db.update(pantryItems).set({ deletedAt: now, updatedAt: now }).where(eq(pantryItems.id, itemId));
}
